export const PortfolioData = [
    {
        id: 1,
        image: "img/portfolio/16.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-3 col-md-6",

        title: "Spay Mobile Banking App",
        category: "graphics",
    },
    {
        id: 2,
        image: "img/portfolio/16.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-3 col-md-6",
        title: "Spay Mobile Banking App",
        category: "all",
    },
    {
        id: 3,
        image: "img/portfolio/16.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-3 col-md-6",
        title: "Spay Mobile Banking App",
        category: "ui-ux",
    },
    {
        id: 5,
        image: "img/portfolio/16.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-3 col-md-6",
        title: "Spay Mobile Banking App",
        category: "consultancy",
    },
    {
        id: 7,
        image: "img/portfolio/17.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-3 col-md-6",
        title: "Spay Mobile Banking App",
        category: "website",
    },
    {
        id: 8,
        image: "img/portfolio/17.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-3 col-md-6",
        title: "Spay Mobile Banking App",
        category: "all",
    },
    {
        id: 9,
        image: "img/portfolio/17.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-3 col-md-6",
        title: "Spay Mobile Banking App",
        category: "ui-ux",
    },
    {
        id: 11,
        image: "img/portfolio/18.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-6 col-lg-12",
        title: "Spay Mobile Banking App",
        category: "consultancy",
    },
    {
        id: 12,
        image: "img/portfolio/18.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-6 col-lg-12",
        title: "Spay Mobile Banking App",
        category: "all",
    },
    {
        id: 13,
        image: "img/portfolio/18.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-6 col-lg-12",
        title: "Spay Mobile Banking App",
        category: "ui-ux",
    },
    {
        id: 15,
        image: "img/portfolio/19.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-6 col-lg-12",
        title: "Spay Mobile Banking App",
        category: "consultancy",
    },
    {
        id: 16,
        image: "img/portfolio/19.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-6 col-lg-12",
        title: "Spay Mobile Banking App",
        category: "all",
    },
    {
        id: 17,
        image: "img/portfolio/19.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-6 col-lg-12",
        title: "Spay Mobile Banking App",
        category: "website",
    },
    {
        id: 19,
        image: "img/portfolio/20.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-3 col-md-6",
        title: "Spay Mobile Banking App",
        category: "graphics",
    },
    {
        id: 20,
        image: "img/portfolio/20.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-3 col-md-6",
        title: "Spay Mobile Banking App",
        category: "all",
    },
    {
        id: 21,
        image: "img/portfolio/20.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-3 col-md-6",
        title: "Spay Mobile Banking App",
        category: "ui-ux",
    },

    {
        id: 23,
        image: "img/portfolio/21.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-3 col-md-6",
        title: "Spay Mobile Banking App",
        category: "website",
    },
    {
        id: 24,
        image: "img/portfolio/21.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-3 col-md-6",
        title: "Spay Mobile Banking App",
        category: "all",
    },
    {
        id: 25,
        image: "img/portfolio/21.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-3 col-md-6",
        title: "Spay Mobile Banking App",
        category: "consultancy",
    },

    {
        id: 27,
        image: "img/portfolio/22.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-3 col-md-6",
        title: "Spay Mobile Banking App",
        category: "website",
    },
    {
        id: 28,
        image: "img/portfolio/22.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-3 col-md-6",
        title: "Spay Mobile Banking App",
        category: "all",
    },
    {
        id: 29,
        image: "img/portfolio/22.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-3 col-md-6",
        title: "Spay Mobile Banking App",
        category: "ui-ux",
    },

    {
        id: 31,
        image: "img/portfolio/23.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-3 col-md-6",
        title: "Spay Mobile Banking App",
        category: "graphics",
    },
    {
        id: 32,
        image: "img/portfolio/23.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-3 col-md-6",
        title: "Spay Mobile Banking App",
        category: "all",
    },
    {
        id: 33,
        image: "img/portfolio/23.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-3 col-md-6",
        title: "Spay Mobile Banking App",
        category: "website",
    },

    {
        id: 35,
        image: "img/portfolio/24.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-6 col-lg-12",
        title: "Spay Mobile Banking Ap",

        category: "consultancy",
    },
    {
        id: 36,
        image: "img/portfolio/24.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-6 col-lg-12",
        title: "Spay Mobile Banking App",
        category: "all",
    },
    {
        id: 37,
        image: "img/portfolio/24.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-6 col-lg-12",
        title: "Spay Mobile Banking App",
        category: "ui-ux",
    },

    {
        id: 39,
        image: "img/portfolio/25.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-6 col-lg-12",
        title: "Spay Mobile Banking App",
        category: "graphics",
    },
    {
        id: 40,
        image: "img/portfolio/25.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-6 col-lg-12",
        title: "Spay Mobile Banking App",
        category: "all",
    },
    {
        id: 41,
        image: "img/portfolio/25.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-6 col-lg-12",
        title: "Spay Mobile Banking App",
        category: "ui-ux",
    },

    {
        id: 43,
        image: "img/portfolio/26.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-3 col-md-6",
        title: "Spay Mobile Banking App",
        category: "graphics",
    },
    {
        id: 44,
        image: "img/portfolio/26.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-3 col-md-6",
        title: "Spay Mobile Banking App",
        category: "all",
    },
    {
        id: 45,
        image: "img/portfolio/26.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-3 col-md-6",
        title: "Spay Mobile Banking App",
        category: "consultancy",
    },

    {
        id: 47,
        image: "img/portfolio/27.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-3 col-md-6",
        title: "Spay Mobile Banking App",
        category: "graphics",
    },
    {
        id: 48,
        image: "img/portfolio/27.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-3 col-md-6",
        title: "Spay Mobile Banking App",
        category: "all",
    },
    {
        id: 49,
        image: "img/portfolio/27.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        classGrid: "col-xl-3 col-md-6",
        title: "Spay Mobile Banking App",
        category: "ui-ux",
    },
];

export const PortfolioOneData = [
    {
        id: 1,
        image: "img/portfolio/05.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "graphics",
    },
    {
        id: 2,
        image: "img/portfolio/05.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "all",
    },
    {
        id: 3,
        image: "img/portfolio/07.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "ui-ux",
    },
    {
        id: 5,
        image: "img/portfolio/05.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "consultancy",
    },
    {
        id: 7,
        image: "img/portfolio/06.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "website",
    },
    {
        id: 8,
        image: "img/portfolio/06.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "all",
    },
    {
        id: 9,
        image: "img/portfolio/08.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "ui-ux",
    },
    {
        id: 10,
        image: "img/portfolio/08.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "all",
    },
    {
        id: 11,
        image: "img/portfolio/07.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "consultancy",
    },
    {
        id: 13,
        image: "img/portfolio/09.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "ui-ux",
    },
    {
        id: 14,
        image: "img/portfolio/09.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "all",
    },
    {
        id: 15,
        image: "img/portfolio/07.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "consultancy",
    },
    {
        id: 17,
        image: "img/portfolio/07.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "website",
    },
    {
        id: 19,
        image: "img/portfolio/06.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "graphics",
    },
    {
        id: 21,
        image: "img/portfolio/12.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "ui-ux",
    },
    {
        id: 22,
        image: "img/portfolio/12.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "all",
    },
    {
        id: 23,
        image: "img/portfolio/10.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "website",
    },
    {
        id: 24,
        image: "img/portfolio/10.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "all",
    },
    {
        id: 25,
        image: "img/portfolio/10.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "consultancy",
    },
    {
        id: 27,
        image: "img/portfolio/11.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "website",
    },
    {
        id: 28,
        image: "img/portfolio/11.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "all",
    },
    {
        id: 29,
        image: "img/portfolio/13.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "ui-ux",
    },
    {
        id: 30,
        image: "img/portfolio/13.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "all",
    },
    {
        id: 31,
        image: "img/portfolio/08.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "graphics",
    },
    {
        id: 33,
        image: "img/portfolio/13.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "website",
    },
    {
        id: 34,
        image: "img/portfolio/15.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "website",
    },

    {
        id: 35,
        image: "img/portfolio/12.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "consultancy",
    },
    {
        id: 39,
        image: "img/portfolio/09.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "graphics",
    },
    {
        id: 43,
        image: "img/portfolio/11.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "graphics",
    },
    {
        id: 45,
        image: "img/portfolio/14.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "consultancy",
    },
    {
        id: 48,
        image: "img/portfolio/14.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "all",
    },
    {
        id: 47,
        image: "img/portfolio/14.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "graphics",
    },
    {
        id: 49,
        image: "img/portfolio/15.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "graphics",
    },
    {
        id: 50,
        image: "img/portfolio/15.jpg",
        subTitle1: "Design",
        subTitle2: "Development",
        title: "Kikado Mobile App Design",
        category: "all",
    },
];
